# Generated by Django 5.1.4 on 2025-01-07 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelmedi.fakultet')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelmedi.course')),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelmedi.kafedra')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('par_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('present', 'geldi'), ('late', 'gija galdy'), ('reason absent', 'sebapli gelmedi'), ('no reason absent', 'sebapsiz gelmedi')], default='present', max_length=24)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelmedi.group')),
            ],
        ),
    ]
