# Generated by Django 5.1.4 on 2025-01-24 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelmedi', '0002_status_alter_student_full_name_alter_student_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='group',
            name='spec',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Hunarmen'), (1, 'Bakalawr'), (2, 'Bakalawr Dil')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Erkek'), (1, 'Ayal')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='login',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Gelmedi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelmedi.status')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelmedi.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelmedi.teacher')),
            ],
        ),
    ]
